[package]
name = "exercises"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd="2"

[dev-dependencies]
float-cmp = "0.9.0"
